services:
  - type: web
    name: smart-classroom-v2
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ELEVENLABS_KEY
        sync: false
      - key: ANTHROPIC_KEY
        sync: false  
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    nodeVersion: 18
    # Uncomment for production scaling (requires Standard plan or higher)
    # scaling:
    #   minInstances: 1
    #   maxInstances: 3 