services:
  - type: web
    name: smart-classroom-transcription
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ELEVENLABS_KEY
        sync: false
      - key: ANTHROPIC_KEY
        sync: false
    healthCheckPath: /admin
    autoDeploy: true
    nodeVersion: 18.20.5 